# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_claim', models.DateField()),
                ('claim_number', models.PositiveIntegerField()),
                ('claim_description', models.TextField()),
                ('claim_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=65)),
                ('email', models.CharField(blank=True, max_length=65)),
                ('premium', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(blank=True, max_length=65)),
                ('limit_of_liability', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='britam.Customer')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='britam.Policies')),
            ],
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=65)),
                ('condition', models.TextField()),
                ('background', models.CharField(blank=True, max_length=65)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='britam.Customer')),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='britam.Policies')),
            ],
        ),
        migrations.AddField(
            model_name='claims',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='britam.Customer'),
        ),
    ]
